import type { Metadata } from "next";

import "@hdc-ui/react/clients-style";
import "@hdc-ui/react/components-style";

import "@/common/global.css";

import GlobalProvier from "@/common/components/GlobalProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <GlobalProvier>{children}</GlobalProvier>
      </body>
    </html>
  );
}
